### PR TITLE
Feature/translator fallback behavior

### LINKED ISSUE #45: Fallback behaviour when translation is not found (null, throw, fallback value)
As the title says, allow the user to choice between any of these fallback behaviours:
- return null
- throw an exception
- return a (custom) fallback value

If none of these behaviours is provided, use the default behaviour (return the key).

### PR DESCRIPTION
**Pull request by wbusey0**
Fixes #45

### CODE REVIEW

**Comment by williamhjcho** [comment]
Hi @wbusey0, thanks for the contribution!

due to unresponsiveness from the repo owners, I've forked and migrated the repo to [over here](https://github.com/williamhjcho/i18next/)
which is where the pub dev package is actually published.

Could you open the issue/PR over there instead?
And which version of the package are you using?

**Comment by wbusey0** [comment]
Hi @williamhjcho,

Thanks for your response.
We are using version 0.5.2.
On further inspection, MissingKeyHandler in the dev preview solves the same problem the `orElse` parameter does.

One thing that still misses in that version if the option to return null (`tOrNull`).
If you think (parts of) this PR can be a contribution I will gradly open a new PR.

PS: the repository linked in pub.dev is still this one, maybe it can be changed to the fork?

**Comment by williamhjcho** [comment]
Yep, it looks like something useful to have, please do add the optional return!

Ah 🤦 thanks for pointing it out, I'll update the URL on the pubspec file

**Comment by wbusey0** [comment]
> n

@williamhjcho what do you think about the orElse parameter? Does it still benefit as a quicker (but less flexible) option next to providing options with a MissingKeyHandler? 

What do you think is the ETA for the 0.6.0 release? Our CI prevents us from using dev preview packages.

**Comment by williamhjcho** [comment]
I just promoted the dev+4 to 0.6.0 👍 

hmm between

```
1. t(..., orElse: () => 'my fallback');
and
2. tOrNull(...)
```

I'd prefer `1`

from the way I'm seeing it right now, the missing key handler is something that is configurable externally (default for all `t` functions)
while the `orElse` is actionable for that individual `t` call.

WDYT?

**Comment by wbusey0** [comment]
I agree the `orElse` parameter is a benefit to the package.

However, I don't think 1. and 2. are exchangeable / server the same purpose. So we would actionally need both of them:

The `orElse` parameter serves to easily return a different fallback value (which defaults to the key).
 This fallback value can be throwing an exception or returning a non-null `String`.

The reason we need a `tOrNull` is we don't want the change the return type of `t()` to `String?`. Much like the `firstWhereOrNull() ` et al. functions in Dart. This in a way also provides the caller with an easy option to provide a fallback value, but also a way to determine the translation for that key cannot be found.

It is exactly this last part that is important for us: we want to log a warning so we can follow-up on missing keys. Right now we have to check if the key equals the translation, but for obvious reasons this causes false positives.

**Comment by williamhjcho** [comment]
Yeah, you're right
The `orElse` should just have the same return signature of the function it belongs to.
And since there are valid use cases where you want the null result, having the `tOrNull` seems like a good idea 👍

**Comment by wbusey0** [comment]
Thank you for your thoughts!
I'll create a PR soon.

**Pull request closed without merging**
